# Respostas do Desafio

In [181]:
from google.cloud import bigquery
from IPython.core.display import display, HTML
from prettytable import PrettyTable

In [182]:
def load_queries(filename):
    with open(filename, 'r') as file:    
        return file.read().split(';')

In [183]:
filename = 'queries.sql'
modelo = 'Onix'
client = bigquery.Client.from_service_account_json('../../Downloads/ancient-medium-220620-dcb918ca109a.json')
query_list = load_queries(filename)

In [184]:
# for query in query_list:
query_job = client.query("""
                         SELECT id, COUNT(id) 
                         FROM dataset_icarros.all_cars 
                         GROUP BY id 
                         HAVING COUNT(id) > 1 
                         LIMIT 10
                         """)
results = query_job.result()  # Waits for job to complete.
for row in results:
    print(row)
    query_job.to_dataframe().shape

## Qual o preço médio do produto por cidade?

In [185]:
query_job = client.query("""
                         SELECT cidade, UF, AVG(preco) as media
                         FROM dataset_icarros.all_cars 
                         WHERE modelo = '{}'
                         GROUP BY cidade, UF
                         ORDER BY cidade
                         """.format(modelo))
results = query_job.result()
t = PrettyTable(['Cidade', 'Preço médio'])
for row in results:
    t.add_row(['{} - {}'.format(row.cidade, row.UF), 'R$ {:,.2f}'.format(row.media).replace('.', '|').replace(',', '.').replace('|', ',')])
    
display(HTML('<h3>Preço médio do produto {} por cidade:</h3>'.format(modelo)))
print(t)

+-----------------------------------------+--------------+
|                  Cidade                 | Preço médio  |
+-----------------------------------------+--------------+
|              Alegrete - RS              | R$ 50.685,00 |
|               Alfenas - MG              | R$ 36.275,00 |
|              Alvorada - RS              | R$ 33.990,00 |
|              Americana - SP             | R$ 42.177,89 |
|               Amparo - SP               | R$ 48.051,67 |
|             Ananindeua - PA             | R$ 42.900,00 |
|              Andradas - MG              | R$ 33.900,00 |
|           Angra dos Reis - RJ           | R$ 36.900,00 |
|              Anápolis - GO              | R$ 37.718,57 |
|        Aparecida de Goiânia - GO        | R$ 36.157,50 |
|              Apucarana - PR             | R$ 39.300,00 |
|               Aracaju - SE              | R$ 36.965,16 |
|              Arapiraca - AL             | R$ 58.000,00 |
|              Arapongas - PR             | R$ 42.900,00 |
|             Araraquara - SP             | R$ 43.145,00 |
|               Araras - SP               | R$ 42.157,14 |
|              Araruama - RJ              | R$ 39.900,00 |
|              Araçatuba - SP             | R$ 42.750,00 |
|                Arujá - SP               | R$ 38.145,00 |
|                Assis - SP               | R$ 38.400,00 |
|            Astolfo Dutra - MG           | R$ 40.500,00 |
|               Atibaia - SP              | R$ 39.260,00 |
|                Avaré - SP               | R$ 42.245,00 |
|                Bagé - RS                | R$ 49.810,00 |
|         Balneário Camboriú - SC         | R$ 36.900,00 |
|               Bariri - SP               | R$ 42.139,00 |
|             Barra Mansa - RJ            | R$ 38.811,76 |
|           Barra do Garças - MT          | R$ 38.900,00 |
|           Barra do Piraí - RJ           | R$ 38.800,00 |
|              Barreiras - BA             | R$ 38.990,00 |
|              Barretos - SP              | R$ 45.037,61 |
|               Barueri - SP              | R$ 38.613,23 |
|               Bastos - SP               | R$ 38.750,00 |
|              Batatais - SP              | R$ 37.400,00 |
|                Bauru - SP               | R$ 36.887,22 |
|              Bebedouro - SP             | R$ 38.925,00 |
|           Belo Horizonte - MG           | R$ 39.978,15 |
|                Belém - PA               | R$ 39.679,29 |
|           Bento Gonçalves - RS          | R$ 41.400,00 |
|                Betim - MG               | R$ 37.900,00 |
|               Birigüi - SP              | R$ 35.000,00 |
|              Blumenau - SC              | R$ 41.687,65 |
|              Boa Vista - RR             | R$ 39.660,00 |
|               Boituva - SP              | R$ 41.450,00 |
|              Botucatu - SP              | R$ 35.883,17 |
|              Bragança - PA              | R$ 43.000,00 |
|          Bragança Paulista - SP         | R$ 38.619,41 |
|              Brasília - DF              | R$ 42.913,18 |
|             Brazlândia - DF             | R$ 31.990,00 |
|               Brusque - SC              | R$ 43.485,71 |
|              Cabedelo - PB              | R$ 35.990,00 |
|              Cabo Frio - RJ             | R$ 40.100,00 |
|              Cabreúva - SP              | R$ 46.900,00 |
|          Cachoeira do Sul - RS          | R$ 37.900,00 |
|        Cachoeiras de Macacu - RJ        | R$ 43.900,00 |
|            Cachoeirinha - RS            | R$ 46.900,00 |
|       Cachoeiro de Itapemirim - ES      | R$ 41.345,00 |
|              Caieiras - SP              | R$ 41.733,33 |
|               Cajamar - SP              | R$ 37.200,00 |
|               Camaquã - RS              | R$ 40.190,00 |
|              Camboriú - SC              | R$ 33.500,00 |
|           Campina Grande - PB           | R$ 36.938,57 |
|        Campina Grande do Sul - PR       | R$ 34.900,00 |
|              Campinas - SP              | R$ 38.706,10 |
|            Campo Grande - MS            | R$ 37.975,71 |
|             Campo Largo - PR            | R$ 42.250,00 |
|            Campo Mourão - PR            | R$ 43.971,82 |
|            Campos Novos - SC            | R$ 36.400,00 |
|               Canoas - RS               | R$ 42.042,80 |
|              Capinzal - SC              | R$ 37.920,00 |
|            Caraguatatuba - SP           | R$ 37.823,33 |
|              Carambeí - PR              | R$ 37.300,00 |
|             Carapicuíba - SP            | R$ 41.511,40 |
|              Carazinho - RS             | R$ 33.390,00 |
|              Cariacica - ES             | R$ 33.400,00 |
|               Carpina - PE              | R$ 42.822,50 |
|               Caruaru - PE              | R$ 40.745,00 |
|              Cascavel - PR              | R$ 39.855,00 |
|              Castanhal - PA             | R$ 38.000,00 |
|               Catalão - GO              | R$ 33.000,00 |
|              Catanduva - SP             | R$ 37.900,00 |
|            Caxias do Sul - RS           | R$ 40.042,20 |
|               Caçador - SC              | R$ 42.900,00 |
|              Ceilândia - DF             | R$ 52.900,00 |
|               Chapecó - SC              | R$ 40.850,00 |
|              Cianorte - PR              | R$ 35.000,00 |
|            Cocal do Sul - SC            | R$ 63.990,00 |
|              Colatina - ES              | R$ 41.079,80 |
|               Colombo - PR              | R$ 35.233,33 |
|        Conceição das Alagoas - MG       | R$ 40.000,00 |
|        Conselheiro Lafaiete - MG        | R$ 41.120,00 |
|              Contagem - MG              | R$ 40.997,50 |
|         Coronel Fabriciano - MG         | R$ 40.000,00 |
|             Cosmópolis - SP             | R$ 39.500,00 |
|                Cotia - SP               | R$ 38.930,00 |
|              Criciúma - SC              | R$ 37.952,73 |
|             Cristalina - GO             | R$ 47.000,00 |
|              Cruz Alta - RS             | R$ 34.900,00 |
|               Cuiabá - MT               | R$ 38.255,38 |
|              Curitiba - PR              | R$ 40.180,65 |
|               Diadema - SP              | R$ 36.984,54 |
|             Divinópolis - MG            | R$ 36.700,00 |
|              Dourados - MS              | R$ 39.572,50 |
|           Duque de Caxias - RJ          | R$ 46.726,19 |
|               Erechim - RS              | R$ 33.500,00 |
|      Espírito Santo do Pinhal - SP      | R$ 40.291,74 |
|              Eunápolis - BA             | R$ 37.300,00 |
|               Extrema - MG              | R$ 37.036,00 |
|         Fazenda Rio Grande - PR         | R$ 36.733,33 |
|          Feira de Santana - BA          | R$ 35.621,43 |
|            Florianópolis - SC           | R$ 39.492,64 |
|               Formiga - MG              | R$ 36.000,00 |
|            Forquilhinha - SC            | R$ 46.990,00 |
|              Fortaleza - CE             | R$ 40.563,24 |
|            Foz do Iguaçu - PR           | R$ 41.866,67 |
|              Fraiburgo - SC             | R$ 36.700,00 |
|               Franca - SP               | R$ 41.022,50 |
|        Frederico Westphalen - RS        | R$ 33.390,00 |
|               Frutal - MG               | R$ 41.000,00 |
|              Garanhuns - PE             | R$ 35.745,00 |
|               Glória - RS               | R$ 39.400,00 |
|               Goioerê - PR              | R$ 43.744,55 |
|               Goiânia - GO              | R$ 49.707,17 |
|        Governador Valadares - MG        | R$ 39.516,50 |
|              Gravataí - RS              | R$ 36.888,82 |
|              Guanambi - BA              | R$ 33.553,00 |
|          Guarantã do Norte - MT         | R$ 35.000,00 |
|              Guarapari - ES             | R$ 33.990,00 |
|             Guarapuava - PR             | R$ 38.354,44 |
|            Guaratinguetá - SP           | R$ 43.313,33 |
|               Guarujá - SP              | R$ 38.380,00 |
|              Guarulhos - SP             | R$ 36.009,11 |
|                Guará - DF               | R$ 40.800,00 |
|               Guaxupé - MG              | R$ 42.900,00 |
|             Hortolândia - SP            | R$ 36.045,00 |
|               Ibirité - MG              | R$ 32.900,00 |
|              Ibitinga - SP              | R$ 41.309,78 |
|                Ijuí - RS                | R$ 37.400,00 |
|             Indaiatuba - SP             | R$ 43.656,67 |
|              Ipatinga - MG              | R$ 35.700,00 |
|              Itabaiana - SE             | R$ 31.500,00 |
|               Itabira - MG              | R$ 40.000,00 |
|              Itaboraí - RJ              | R$ 38.175,00 |
|               Itabuna - BA              | R$ 37.231,50 |
|               Itaguaí - RJ              | R$ 36.118,00 |
|               Itajaí - SC               | R$ 42.349,84 |
|               Itajubá - MG              | R$ 41.557,14 |
|              Itapagipe - MG             | R$ 32.900,00 |
|               Itapema - SC              | R$ 37.700,00 |
|              Itaperuna - RJ             | R$ 42.000,00 |
|            Itapetininga - SP            | R$ 36.900,00 |
|           Itaquaquecetuba - SP          | R$ 38.695,00 |
|               Itararé - SP              | R$ 40.699,00 |
|               Itatiba - SP              | R$ 37.500,00 |
|                 Itu - SP                | R$ 43.874,00 |
|              Ituiutaba - MG             | R$ 36.450,00 |
|              Itumbiara - GO             | R$ 36.750,00 |
|              Itápolis - SP              | R$ 44.633,33 |
|              Ivaiporã - PR              | R$ 39.300,00 |
|                Içara - SC               | R$ 34.990,00 |
|                Iúna - ES                | R$ 40.000,00 |
| Jaboatão (Jaboatão dos Guararapes) - PE | R$ 38.296,67 |
|       Jaboatão dos Guararapes - PE      | R$ 45.323,33 |
|               Jacareí - SP              | R$ 44.519,49 |
|              Jacutinga - MG             | R$ 45.000,00 |
|             Jaguaquara - BA             | R$ 47.400,00 |
|             Jaguariúna - SP             | R$ 49.725,00 |
|                Jales - SP               | R$ 38.900,00 |
|               Jandira - SP              | R$ 37.953,33 |
|               Jaraguá - GO              | R$ 33.000,00 |
|           Jaraguá do Sul - SC           | R$ 40.136,00 |
|                Jataí - GO               | R$ 38.485,71 |
|                 Jaú - SP                | R$ 39.299,60 |
|               Jequié - BA               | R$ 32.500,00 |
|               Joaçaba - SC              | R$ 36.433,33 |
|              Joinville - SC             | R$ 37.386,17 |
|             João Pessoa - PB            | R$ 36.610,00 |
|              Juazeiro - BA              | R$ 38.857,14 |
|          Juazeiro do Norte - CE         | R$ 40.338,17 |
|            Juiz de Fora - MG            | R$ 39.815,28 |
|               Jundiaí - SP              | R$ 41.589,88 |
|                Lages - SC               | R$ 38.290,00 |
|               Lajeado - RS              | R$ 41.900,00 |
|          Laranjal Paulista - SP         | R$ 46.000,00 |
|          Lauro de Freitas - BA          | R$ 38.296,15 |
|                Leme - SP                | R$ 49.076,00 |
|          Lençóis Paulista - SP          | R$ 42.096,67 |
|               Limeira - SP              | R$ 46.228,33 |
|              Linhares - ES              | R$ 46.610,00 |
|                Lins - SP                | R$ 39.000,00 |
|              Londrina - PR              | R$ 42.210,88 |
|               Lorena - SP               | R$ 34.490,00 |
|                 Luz - MG                | R$ 35.900,00 |
|              Luziânia - GO              | R$ 32.900,00 |
|               Macapá - AP               | R$ 40.566,67 |
|                Macaé - RJ               | R$ 40.245,00 |
|               Maceió - AL               | R$ 37.163,57 |
|               Manaus - AM               | R$ 45.712,15 |
|              Manhuaçu - MG              | R$ 40.663,33 |
|               Mantena - MG              | R$ 37.850,00 |
|              Maracanaú - CE             | R$ 42.900,00 |
|              Marialva - PR              | R$ 39.500,00 |
|               Maricá - RJ               | R$ 29.800,00 |
|               Maringá - PR              | R$ 40.097,03 |
|               Marília - SP              | R$ 40.920,00 |
|             Matozinhos - MG             | R$ 32.900,00 |
|                Matão - SP               | R$ 44.079,00 |
|                Mauá - SP                | R$ 40.447,50 |
|             Medianeira - PR             | R$ 46.900,00 |
|              Mesquita - RJ              | R$ 35.263,33 |
|           Miguel Pereira - RJ           | R$ 35.900,00 |
|              Mineiros - GO              | R$ 37.440,00 |
|           Mogi das Cruzes - SP          | R$ 37.113,23 |
|             Mogi-Guaçu - SP             | R$ 38.301,67 |
|             Mogi-Mirim - SP             | R$ 38.638,00 |
|             Monte Alto - SP             | R$ 40.000,00 |
|         Monte Azul Paulista - SP        | R$ 34.950,00 |
|            Montes Claros - MG           | R$ 39.990,00 |
|               Mossoró - RN              | R$ 39.643,58 |
|             Muzambinho - MG             | R$ 55.396,67 |
|                Natal - RN               | R$ 38.689,50 |
|             Navegantes - SC             | R$ 36.800,00 |
|               Niterói - RJ              | R$ 48.173,45 |
|            Nova Friburgo - RJ           | R$ 37.372,73 |
|             Nova Iguaçu - RJ            | R$ 38.027,62 |
|             Nova Odessa - SP            | R$ 38.266,67 |
|            Nova Serrana - MG            | R$ 32.000,00 |
|            Novo Hamburgo - RS           | R$ 39.415,20 |
|               Olinda - PE               | R$ 40.901,56 |
|               Olímpia - SP              | R$ 35.000,00 |
|              Orlândia - SP              | R$ 41.500,00 |
|               Osasco - SP               | R$ 38.936,63 |
|               Osório - RS               | R$ 41.704,29 |
|               Palhoça - SC              | R$ 36.760,00 |
|               Palmas - TO               | R$ 36.220,00 |
|         Palmeira dos Índios - AL        | R$ 36.900,00 |
|              Palotina - PR              | R$ 51.000,00 |
|               Panambi - RS              | R$ 33.390,00 |
|         Paraguaçu Paulista - SP         | R$ 37.000,00 |
|              Paranaguá - PR             | R$ 51.823,33 |
|              Paranavaí - PR             | R$ 39.000,00 |
|             Parnamirim - RN             | R$ 37.400,00 |
|             Passa Tempo - MG            | R$ 37.800,00 |
|             Passo Fundo - RS            | R$ 39.682,72 |
|             Pato Branco - PR            | R$ 39.717,50 |
|           Patos de Minas - MG           | R$ 42.445,00 |
|             Patrocínio - MG             | R$ 39.150,00 |
|           Paty do Alferes - RJ          | R$ 35.900,00 |
|              Paulínia - SP              | R$ 35.590,91 |
|              Pedreira - SP              | R$ 38.626,67 |
|               Pelotas - RS              | R$ 38.226,30 |
|                Penha - SC               | R$ 36.100,00 |
|              Penápolis - SP             | R$ 33.000,00 |
|              Petrolina - PE             | R$ 33.875,00 |
|             Petrópolis - RJ             | R$ 37.297,50 |
|             Piracicaba - SP             | R$ 38.680,00 |
|               Piraju - SP               | R$ 37.750,00 |
|              Piraquara - PR             | R$ 33.500,00 |
|            Pirassununga - SP            | R$ 46.116,67 |
|            Ponta Grossa - PR            | R$ 42.612,86 |
|             Ponte Nova - MG             | R$ 37.490,00 |
|            Porto Alegre - RS            | R$ 39.673,03 |
|             Porto Belo - SC             | R$ 39.900,00 |
|             Porto Feliz - SP            | R$ 33.500,00 |
|             Porto Velho - RO            | R$ 38.740,00 |
|                Posse - GO               | R$ 39.900,00 |
|            Pouso Alegre - MG            | R$ 40.631,33 |
|           Poços de Caldas - MG          | R$ 42.136,00 |
|            Praia Grande - SP            | R$ 38.552,33 |
|                Prata - MG               | R$ 41.000,00 |
|         Presidente Prudente - SP        | R$ 38.118,89 |
|                Quatá - SP               | R$ 37.800,00 |
|              Querência - MT             | R$ 53.000,00 |
|               Recife - PE               | R$ 40.219,42 |
|              Registro - SP              | R$ 37.333,33 |
|               Resende - RJ              | R$ 39.414,29 |
|           Ribeirão Preto - SP           | R$ 41.310,12 |
|             Rio Bonito - RJ             | R$ 37.900,00 |
|             Rio Branco - AC             | R$ 60.000,00 |
|          Rio Branco do Sul - PR         | R$ 45.900,00 |
|              Rio Claro - SP             | R$ 44.141,43 |
|             Rio Grande - RS             | R$ 34.900,00 |
|              Rio Verde - GO             | R$ 37.632,50 |
|           Rio das Ostras - RJ           | R$ 41.132,50 |
|           Rio de Janeiro - RJ           | R$ 41.072,31 |
|             Rio do Sul - SC             | R$ 39.778,33 |
|           Rolim de Moura - RO           | R$ 38.000,00 |
|                Salto - SP               | R$ 33.990,00 |
|              Salvador - BA              | R$ 39.915,98 |
|          Santa Cruz do Sul - RS         | R$ 38.652,00 |
|             Santa Maria - RS            | R$ 47.315,71 |
|        Santa Rita do Sapucaí - MG       | R$ 38.000,00 |
|             Santa Rosa - RS             | R$ 52.570,77 |
|        Santa Rosa de Viterbo - SP       | R$ 40.400,00 |
|        Santana do Livramento - RS       | R$ 53.250,77 |
|              Santiago - RS              | R$ 51.940,00 |
|             Santo André - SP            | R$ 38.902,57 |
|       Santo Antônio de Jesus - BA       | R$ 36.492,50 |
|            Santo Ângelo - RS            | R$ 51.940,00 |
|               Santos - SP               | R$ 38.256,50 |
|           Sapucaia do Sul - RS          | R$ 39.000,00 |
|                Serra - ES               | R$ 38.492,50 |
|             Sertãozinho - SP            | R$ 37.990,00 |
|             Sete Lagoas - MG            | R$ 45.058,46 |
|             Sobradinho - DF             | R$ 39.400,00 |
|               Sobral - CE               | R$ 47.956,67 |
|              Sorocaba - SP              | R$ 40.784,20 |
|               Sumaré - SP               | R$ 35.442,31 |
|               Surubim - PE              | R$ 52.000,00 |
|               Suzano - SP               | R$ 37.561,64 |
|          São Bento do Sul - SC          | R$ 36.175,00 |
|        São Bernardo do Campo - SP       | R$ 38.998,28 |
|              São Borja - RS             | R$ 51.940,00 |
|         São Caetano do Sul - SP         | R$ 43.532,44 |
|             São Carlos - SP             | R$ 37.697,22 |
|             São Gabriel - RS            | R$ 51.940,00 |
|             São Gonçalo - RJ            | R$ 39.631,67 |
|             São Gotardo - MG            | R$ 38.000,00 |
|              São José - SC              | R$ 39.035,87 |
|        São José do Rio Pardo - SP       | R$ 38.225,00 |
|        São José do Rio Preto - SP       | R$ 39.135,16 |
|         São José dos Campos - SP        | R$ 42.136,89 |
|        São José dos Pinhais - PR        | R$ 40.151,11 |
|          São João Del Rei - MG          | R$ 28.900,00 |
|        São João da Boa Vista - SP       | R$ 34.722,50 |
|         São João de Meriti - RJ         | R$ 33.420,37 |
|            São Leopoldo - RS            | R$ 38.559,26 |
|            São Lourenço - MG            | R$ 40.915,56 |
|          São Luiz Gonzaga - RS          | R$ 34.900,00 |
|              São Luís - MA              | R$ 39.335,33 |
|      São Luís de Montes Belos - GO      | R$ 36.900,00 |
|             São Mateus - ES             | R$ 33.740,00 |
|              São Paulo - SP             | R$ 40.089,13 |
|         São Pedro da Aldeia - RJ        | R$ 37.422,50 |
|             São Vicente - SP            | R$ 39.265,00 |

## Qual a cidade que possui mais ofertas do produto?

In [186]:
query_job = client.query("""
                         SELECT cidade, UF, COUNT(id) as total
                         FROM dataset_icarros.all_cars 
                         WHERE modelo = '{}'
                         GROUP BY cidade, UF
                         ORDER BY total DESC
                         LIMIT 1
                         """.format(modelo))
results = query_job.result()
t = PrettyTable(['Cidade', 'Total'])
for row in results:
    t.add_row(['{} - {}'.format(row.cidade, row.UF), '{}'.format(row.total)])
display(HTML('<h3>Cidade com mais ofertas do produto {}:</h3>'.format(modelo)))
print(t)

+----------------+-------+
|     Cidade     | Total |
+----------------+-------+
| São Paulo - SP |  811  |
+----------------+-------+

## Liste os 5 mais baratos e o mais caro.

In [187]:
query_job = client.query("""
                         SELECT versao, ano, km, cidade, UF, preco
                         FROM dataset_icarros.all_cars 
                         WHERE modelo = '{}'
                         ORDER BY preco ASC
                         LIMIT 5
                         """.format(modelo))
results = query_job.result()
t = PrettyTable(['Versão', 'Cidade', 'Ano', 'Km', 'Preço'])
print()
for row in results:
    t.add_row(['{}'.format(row.versao), 
               '{} - {}'.format(row.cidade, row.UF),
               '{}'.format(row.ano), 
               '{}'.format(row.km), 
               'R$ {:,.2f}'.format(row.preco).replace('.', '|').replace(',', '.').replace('|', ',')])
display(HTML('<h3>5 mais baratos:</h3>'))
print(t)

+-------------------+----------------------------+------------+--------+--------------+
|       Versão      |           Cidade           |    Ano     |   Km   |    Preço     |
+-------------------+----------------------------+------------+--------+--------------+
| Onix 1.0 LS SPE/4 |       São Paulo - SP       | 2014/ 2015 | 77642  | R$ 24.900,00 |
| Onix 1.0 LS SPE/4 |    Rio de Janeiro - RJ     | 2015/ 2015 |  N/D   | R$ 25.900,00 |
| Onix 1.0 LT SPE/4 | São Bernardo do Campo - SP | 2013/ 2013 | 93545  | R$ 26.900,00 |
| Onix 1.0 LT SPE/4 |  São João de Meriti - RJ   | 2012/ 2013 |  N/D   | R$ 26.900,00 |
| Onix 1.0 LS SPE/4 |       Brasília - DF        | 2013/ 2014 | 113900 | R$ 26.900,00 |
+-------------------+----------------------------+------------+--------+--------------+

In [188]:
query_job = client.query("""
                         SELECT versao, ano, km, cidade, UF, preco
                         FROM dataset_icarros.all_cars 
                         WHERE modelo = '{}'
                         ORDER BY preco DESC
                         LIMIT 1
                         """.format(modelo))
results = query_job.result()
t = PrettyTable(['Versão', 'Cidade', 'Ano', 'Km', 'Preço'])
print()
for row in results:
    t.add_row(['{}'.format(row.versao), 
               '{} - {}'.format(row.cidade, row.UF),
               '{}'.format(row.ano), 
               '{}'.format(row.km), 
               'R$ {:,.2f}'.format(row.preco).replace('.', '|').replace(',', '.').replace('|', ',')])
display(HTML('<h3>O mais caro:</h3>'))
print(t)

+--------------------------+--------------+------------+----+--------------+
|          Versão          |    Cidade    |    Ano     | Km |    Preço     |
+--------------------------+--------------+------------+----+--------------+
| Onix 1.4 LTZ SPE/4 (Aut) | Xanxerê - SC | 2018/ 2019 | 0  | R$ 72.000,00 |
+--------------------------+--------------+------------+----+--------------+

In [189]:
query_job = client.query("""
                         SELECT COUNT (*) as total FROM (
                             SELECT DISTINCT cidade, UF
                             FROM dataset_icarros.all_cars 
                             WHERE modelo = '{}'
                                 AND CIDADE IS NOT NULL 
                                 AND CIDADE <> ''
                             GROUP BY cidade, UF
                             ORDER BY cidade
                         )
                         """.format(modelo))
results = query_job.result()  # Waits for job to complete.
# print(results.result())
t = PrettyTable(['Total de Cidades'])
for row in results:
    t.add_row(['{}'.format(row.total)])
display(HTML('<h4>Quantas cidades possuem anúncios do produto {}?</h4>'.format(modelo)))    
print(t)

+------------------+
| Total de Cidades |
+------------------+
|       373        |
+------------------+

In [190]:
query_job = client.query("""
                         SELECT COUNT (*) as total FROM (
                             SELECT DISTINCT UF
                             FROM dataset_icarros.all_cars 
                             WHERE modelo = '{}'
                                 AND UF IS NOT NULL 
                                 AND UF <> ''
                             GROUP BY UF
                             ORDER BY UF
                         )
                         """.format(modelo))
results = query_job.result()
t = PrettyTable(['Total de Estados'])
for row in results:
    t.add_row(['{}'.format(row.total)])
display(HTML('<h4>Quantos estados possuem anúncios do produto {}?</h4>'.format(modelo)))    
print(t)

+------------------+
| Total de Estados |
+------------------+
|        27        |
+------------------+

# Considerando todos os carros

## Qual o preço médio do produto por cidade?

In [191]:
modelo2 = """ 'Carro' """

In [196]:
query_job = client.query("""
                         SELECT cidade, UF, AVG(preco) as media
                         FROM dataset_icarros.all_cars 
                         GROUP BY cidade, UF
                         ORDER BY cidade
                         """)
results = query_job.result()
t = PrettyTable(['Cidade', 'Preço médio'])
for row in results:
    if row.cidade == '':
        cidade = 'N/D'
    else:
        cidade = row.cidade
    t.add_row(['{} - {}'.format(cidade, row.UF), 'R$ {:,.2f}'.format(row.media).replace('.', '|').replace(',', '.').replace('|', ',')])
    
display(HTML('<h3>Preço médio do produto {} por cidade:</h3>'.format(modelo2)))
print(t)

+-----------------------------------------+---------------+
|                  Cidade                 |  Preço médio  |
+-----------------------------------------+---------------+
|                  N/D -                  |  R$ 25.000,00 |
|               Abaeté - MG               |  R$ 49.340,00 |
|            Abreu e Lima - PE            |  R$ 52.000,00 |
|               Acreúna - GO              |  R$ 39.900,00 |
|             Adamantina - SP             |  R$ 52.000,00 |
|             Agrolândia - SC             |  R$ 75.000,00 |
|                Aguaí - SP               |  R$ 54.825,00 |
|                Agudo - RS               |  R$ 9.000,00  |
|               Agudos - SP               |  R$ 35.000,00 |
|               Aimorés - MG              |  R$ 63.000,00 |
|             Alagoa Nova - PB            |  R$ 19.000,00 |
|             Alagoinhas - BA             |  R$ 64.049,20 |
|               Alegre - ES               |  R$ 51.000,00 |
|              Alegrete - RS              |  R$ 61.260,31 |
|               Alfenas - MG              |  R$ 42.307,08 |
|              Almenara - MG              |  R$ 28.000,00 |
|         Almirante Tamandaré - PR        |  R$ 13.000,00 |
|            Alto Piquiri - PR            |  R$ 35.800,00 |
|              Alvorada - RS              |  R$ 38.558,00 |
|              Americana - SP             |  R$ 58.611,77 |
|               Amparo - SP               |  R$ 50.433,79 |
|         Américo Brasiliense - SP        |  R$ 24.187,27 |
|             Ananindeua - PA             |  R$ 78.420,59 |
|              Andorinha - BA             |  R$ 46.000,00 |
|              Andradas - MG              |  R$ 41.910,57 |
|              Andradina - SP             |  R$ 95.250,00 |
|           Angra dos Reis - RJ           |  R$ 44.830,91 |
|               Anhumas - SP              | R$ 132.000,00 |
|              Antonina - PR              |  R$ 50.000,00 |
|          Antônio Gonçalves - BA         |  R$ 22.000,00 |
|              Anápolis - GO              |  R$ 50.052,04 |
|              Aparecida - PB             |  R$ 93.000,00 |
|        Aparecida de Goiânia - GO        |  R$ 41.321,38 |
|              Apucarana - PR             |  R$ 50.454,23 |
|               Aracaju - SE              |  R$ 49.832,24 |
|               Aracruz - ES              |  R$ 62.285,00 |
|              Araguari - MG              |  R$ 38.506,67 |
|              Araguaína - TO             |  R$ 50.000,00 |
|              Arapiraca - AL             |  R$ 52.674,32 |
|              Arapongas - PR             |  R$ 42.910,18 |
|              Araranguá - SC             |  R$ 49.958,18 |
|             Araraquara - SP             |  R$ 46.448,67 |
|               Araras - SP               |  R$ 47.458,55 |
|              Araripina - PE             |  R$ 96.950,00 |
|              Araruama - RJ              |  R$ 53.230,51 |
|               Araruna - PR              |  R$ 13.900,00 |
|              Araucária - PR             | R$ 152.000,00 |
|                Araxá - MG               |  R$ 50.911,15 |
|              Araçatuba - SP             |  R$ 55.443,89 |
|         Araçoiaba da Serra - SP         |  R$ 23.400,00 |
|              Arceburgo - MG             |  R$ 55.000,00 |
|              Arcoverde - PE             | R$ 202.600,00 |
|                Areal - RJ               |  R$ 25.250,00 |
|            Areia Branca - RN            |  R$ 42.900,00 |
|              Ariquemes - RO             |  R$ 63.666,67 |
|          Armação de Búzios - RJ         |  R$ 30.630,00 |
|           Artur Nogueira - SP           |  R$ 36.500,00 |
|               Aruanã - GO               |  R$ 26.500,00 |
|                Arujá - SP               |  R$ 53.825,47 |
|                Assis - SP               |  R$ 50.223,94 |
|         Assis Chateaubriand - PR        |  R$ 50.666,43 |
|            Astolfo Dutra - MG           |  R$ 30.291,67 |
|               Atibaia - SP              |  R$ 43.728,42 |
|                Avaré - SP               |  R$ 47.461,11 |
|             Açailândia - MA             |  R$ 61.000,00 |
|               Bacabal - MA              |  R$ 51.967,65 |
|              Bacabeira - MA             |  R$ 23.000,00 |
|                Bagé - RS                |  R$ 60.847,60 |
|             Baianópolis - BA            |  R$ 38.900,00 |
|         Balneário Camboriú - SC         |  R$ 80.585,18 |
|             Balsa Nova - PR             |  R$ 75.000,00 |
|               Balsas - MA               |  R$ 63.418,90 |
|            Bandeirantes - PR            |  R$ 78.500,00 |
|              Barbacena - MG             |  R$ 50.000,00 |
|               Bariri - SP               |  R$ 49.136,00 |
|             Barra Mansa - RJ            |  R$ 38.888,57 |
|           Barra do Corda - MA           |  R$ 18.000,00 |
|           Barra do Garças - MT          |  R$ 61.209,91 |
|           Barra do Piraí - RJ           |  R$ 42.251,44 |
|          Barra do Ribeiro - RS          |  R$ 14.000,00 |
|              Barreiras - BA             |  R$ 60.455,70 |
|              Barretos - SP              |  R$ 55.260,23 |
|               Barueri - SP              |  R$ 78.234,39 |
|               Bastos - SP               |  R$ 25.700,00 |
|              Batatais - SP              |  R$ 42.113,89 |
|                Bauru - SP               |  R$ 53.152,65 |
|              Bebedouro - SP             |  R$ 45.126,72 |
|              Bela Cruz - CE             |  R$ 13.500,00 |
|            Belford Roxo - RJ            |  R$ 30.950,00 |
|           Belo Horizonte - MG           |  R$ 53.410,41 |
|                Belém - PA               |  R$ 51.569,40 |
|       Belém de São Francisco - PE       |  R$ 39.990,00 |
|           Bento Gonçalves - RS          |  R$ 73.067,41 |
|              Bertioga - SP              |  R$ 21.600,00 |
|                Betim - MG               |  R$ 44.860,67 |
|              Bezerros - PE              |  R$ 75.946,15 |
|               Birigüi - SP              |  R$ 34.625,00 |
|              Blumenau - SC              |  R$ 63.224,86 |
|              Boa Vista - RR             |  R$ 50.020,00 |
|              Bocaiúva - MG              |  R$ 26.000,00 |
|               Boituva - SP              |  R$ 46.989,29 |
|            Bom Despacho - MG            |  R$ 32.154,92 |
|             Bom Jardim - RJ             |  R$ 41.592,31 |
|          Bom Jesus da Lapa - BA         |  R$ 42.000,00 |
|         Bom Jesus da Penha - MG         |  R$ 51.000,00 |
|        Bom Jesus dos Perdões - SP       |  R$ 19.494,50 |
|            Bom Princípio - RS           |  R$ 38.500,00 |
|             Bom Repouso - MG            |  R$ 28.000,00 |
|          Bom Retiro do Sul - RS         |  R$ 5.000,00  |
|              Bombinhas - SC             | R$ 187.000,00 |
|               Bonito - MS               |  R$ 23.000,00 |
|              Botucatu - SP              |  R$ 51.157,10 |
|              Bragança - PA              |  R$ 36.000,00 |
|          Bragança Paulista - SP         |  R$ 45.633,50 |
|              Brasília - DF              |  R$ 56.262,73 |
|          Brasília de Minas - MG         |  R$ 12.500,00 |
|             Brazlândia - DF             |  R$ 35.990,83 |
|               Brotas - SP               |  R$ 42.000,00 |
|             Brumadinho - MG             |  R$ 25.000,00 |
|               Brumado - BA              |  R$ 75.923,81 |
|               Brusque - SC              |  R$ 73.646,97 |
|              Cabedelo - PB              | R$ 114.197,46 |
|              Cabo Frio - RJ             |  R$ 43.668,97 |
|       Cabo de Santo Agostinho - PE      |  R$ 46.605,00 |
|              Cabreúva - SP              |  R$ 56.453,46 |
|           Cachoeira Alta - GO           |  R$ 28.600,00 |
|          Cachoeira Dourada - MG         |  R$ 85.000,00 |
|          Cachoeira do Sul - RS          |  R$ 44.407,19 |
|        Cachoeiras de Macacu - RJ        |  R$ 53.036,36 |
|            Cachoeirinha - RS            |  R$ 49.306,25 |
|       Cachoeiro de Itapemirim - ES      |  R$ 61.638,86 |
|               Cacoal - RO               |  R$ 44.250,00 |
|               Caculé - BA               |  R$ 35.000,00 |
|                Caeté - MG               |  R$ 80.000,00 |
|             Cafelândia - SP             |  R$ 23.500,00 |
|             Cafelândia - PR             |  R$ 24.000,00 |
|                Caicó - RN               |  R$ 51.106,04 |
|              Caieiras - SP              |  R$ 44.939,81 |
|               Cajamar - SP              |  R$ 67.922,20 |
|             Cajazeiras - PB             |  R$ 47.809,66 |
|            Caldas Novas - GO            |  R$ 43.290,00 |
|               Camaquã - RS              |  R$ 64.236,29 |
|             Camaragibe - PE             |  R$ 22.000,00 |
|              Camaçari - BA              |  R$ 26.500,00 |
|              Camboriú - SC              |  R$ 44.947,50 |
|               Cambuci - RJ              |  R$ 44.000,00 |
|               Cambuí - MG               |  R$ 8.000,00  |
|                Cambé - PR               |  R$ 42.481,82 |
|           Campina Grande - PB           |  R$ 51.645,58 |
|        Campina Grande do Sul - PR       |  R$ 36.187,40 |
|              Campinas - SP              |  R$ 46.640,28 |
|        Campo Alegre de Goiás - GO       |  R$ 15.000,00 |
|             Campo Belo - MG             |  R$ 74.383,85 |
|              Campo Bom - RS             |  R$ 33.900,00 |
|            Campo Grande - MS            |  R$ 62.146,62 |
|             Campo Largo - PR            |  R$ 54.983,96 |
|        Campo Limpo Paulista - SP        |  R$ 27.387,50 |
|            Campo Mourão - PR            |  R$ 65.758,21 |
|            Campos Novos - SC            |  R$ 42.914,81 |
|          Campos do Jordão - SP          |  R$ 99.000,00 |
|        Campos dos Goytacazes - RJ       |  R$ 47.783,71 |
|              Cananéia - SP              |  R$ 28.500,00 |
|               Canela - RS               |  R$ 56.878,33 |
|               Canoas - RS               |  R$ 53.009,53 |
|           Capela do Alto - SP           |  R$ 54.000,00 |
|              Capinzal - SC              |  R$ 47.134,04 |
|           Capão da Canoa - RS           |  R$ 45.000,00 |
|            Caraguatatuba - SP           |  R$ 42.950,27 |
|              Carambeí - PR              |  R$ 42.430,35 |
|             Carapicuíba - SP            |  R$ 39.992,60 |
|              Caratinga - MG             |  R$ 50.111,81 |
|              Carazinho - RS             |  R$ 63.977,69 |
|              Cariacica - ES             |  R$ 34.726,75 |
|            Carlos Chagas - MG           |  R$ 16.000,00 |
|         Carmópolis de Minas - MG        |  R$ 48.500,00 |
|               Carpina - PE              |  R$ 55.581,75 |
|               Caruaru - PE              |  R$ 67.693,65 |
|             Casa Branca - SP            |  R$ 48.583,33 |
|              Cascavel - PR              |  R$ 47.761,76 |
|          Casimiro de Abreu - RJ         |  R$ 34.347,37 |
|             Cassilândia - MS            |  R$ 74.500,00 |
|              Castanhal - PA             |  R$ 49.931,57 |
|               Castro - PR               |  R$ 64.817,33 |
|            Castro Alves - BA            |  R$ 30.000,00 |
|             Cataguases - MG             |  R$ 41.472,50 |
|               Catalão - GO              |  R$ 54.184,00 |
|              Catanduva - SP             |  R$ 51.314,29 |
|             Catanduvas - PR             |  R$ 44.000,00 |
|               Catuípe - RS              |  R$ 83.000,00 |
|               Caucaia - CE              |  R$ 27.000,00 |
|               Caxias - MA               |  R$ 95.972,59 |
|            Caxias do Sul - RS           |  R$ 55.542,78 |
|               Caçador - SC              |  R$ 58.319,28 |
|              Caçapava - SP              |  R$ 42.055,67 |
|              Ceilândia - DF             |  R$ 61.730,45 |
|                Ceres - GO               |  R$ 55.083,57 |
|           Cerqueira César - SP          |  R$ 69.900,00 |
|               Chapecó - SC              |  R$ 60.885,15 |
|             Chopinzinho - PR            |  R$ 90.000,00 |
|              Cianorte - PR              |  R$ 57.201,87 |
|          Cidade Ocidental - GO          |  R$ 51.900,00 |
|            Cocal do Sul - SC            |  R$ 71.542,50 |
|              Colatina - ES              |  R$ 51.631,61 |
|               Colombo - PR              |  R$ 34.470,40 |
|        Conceição das Alagoas - MG       |  R$ 40.000,00 |
|         Conceição dos Ouros - MG        |  R$ 36.500,00 |
|               Conchal - SP              |  R$ 38.415,78 |
|              Concórdia - SC             |  R$ 62.396,10 |
|               Confins - MG              |  R$ 18.800,00 |
|        Conselheiro Lafaiete - MG        |  R$ 44.662,04 |
|              Contagem - MG              |  R$ 43.347,75 |
|              Cordeiro - RJ              |  R$ 80.000,00 |
|               Coribe - BA               |  R$ 35.500,00 |
|           Coronel Bicaco - RS           |  R$ 24.000,00 |
|         Coronel Fabriciano - MG         |  R$ 34.000,00 |
|          Coronel Sapucaia - MS          |  R$ 17.740,00 |
|             Cosmópolis - SP             |  R$ 37.787,50 |
|             Costa Rica - MS             |  R$ 48.500,00 |
|                Cotia - SP               |  R$ 49.328,23 |
|                Coxim - MS               |  R$ 44.950,00 |
|              Cravinhos - SP             |  R$ 22.000,00 |
|              Criciúma - SC              |  R$ 51.600,34 |
|             Cristalina - GO             |  R$ 62.766,67 |
|              Cruz Alta - RS             |  R$ 60.279,87 |
|              Cruzeiro - SP              |  R$ 41.500,00 |
|               Cubatão - SP              |  R$ 45.177,78 |
|               Cuiabá - MT               |  R$ 64.765,29 |
|              Curitiba - PR              |  R$ 58.630,73 |
|             Curitibanos - SC            |  R$ 42.618,89 |
|               Cáceres - MT              |  R$ 59.553,18 |
|               Cássia - MG               |  R$ 46.500,00 |
|             Descalvado - SP             |  R$ 37.218,18 |
|               Diadema - SP              |  R$ 36.565,04 |
|             Diamantina - MG             |  R$ 43.669,36 |
|            Dias D'Ávila - BA            |  R$ 76.000,00 |
|               Divino - MG               |  R$ 25.200,00 |
|             Divinópolis - MG            |  R$ 61.875,04 |
|             Dois Irmãos - RS            |  R$ 56.450,00 |
|              Dourados - MS              |  R$ 58.221,86 |
|           Duque de Caxias - RJ          |  R$ 45.801,78 |
|           Eldorado do Sul - RS          |  R$ 50.500,00 |
|           Embu das Artes - SP           |  R$ 30.605,66 |
|             Embu-Guaçu - SP             |  R$ 8.500,00  |
|             Entre Rios - BA             |  R$ 30.000,00 |
|               Erechim - RS              |  R$ 64.863,75 |
|              Espumoso - RS              |  R$ 55.900,00 |
|      Espírito Santo do Pinhal - SP      |  R$ 53.918,42 |
|               Esteio - RS               |  R$ 33.350,00 |
|            Estiva Gerbi - SP            |  R$ 14.500,00 |
|               Estrela - RS              |  R$ 27.000,00 |
|              Estância - SE              |  R$ 28.000,00 |
|           Estância Velha - RS           |  R$ 63.847,37 |
|              Eunápolis - BA             |  R$ 53.623,94 |
|               Eusébio - CE              |  R$ 22.900,00 |
|               Extrema - MG              |  R$ 46.564,57 |
|             Farroupilha - RS            |  R$ 70.250,00 |
|               Faxinal - PR              |  R$ 28.250,00 |
|         Fazenda Rio Grande - PR         |  R$ 35.960,38 |
|             Feira Nova - PE             |  R$ 37.000,00 |
|          Feira de Santana - BA          |  R$ 85.446,52 |
|                Feliz - RS               |  R$ 29.500,00 |
|            Fernandópolis - SP           |  R$ 41.700,00 |
|        Ferraz de Vasconcelos - SP       |  R$ 41.908,67 |
|              Floriano - PI              |  R$ 86.937,05 |
|            Florianópolis - SC           |  R$ 59.665,84 |
|               Formiga - MG              |  R$ 44.607,40 |
|               Formosa - GO              |  R$ 43.535,31 |
|            Forquilhinha - SC            |  R$ 37.549,58 |
|              Fortaleza - CE             |  R$ 57.252,18 |
|            Foz do Iguaçu - PR           |  R$ 52.327,91 |
|              Fraiburgo - SC             |  R$ 48.155,00 |
|               Franca - SP               |  R$ 49.630,86 |
|          Francisco Beltrão - PR         |  R$ 79.633,33 |
|          Francisco Morato - SP          |  R$ 20.000,00 |
|           Franco da Rocha - SP          |  R$ 43.297,50 |
|        Frederico Westphalen - RS        |  R$ 57.154,27 |
|               Frutal - MG               |  R$ 57.221,97 |
|                Gama - DF                |  R$ 37.894,20 |
|              Garanhuns - PE             |  R$ 49.107,05 |
|           General Salgado - SP          |  R$ 41.900,00 |
|              Glorinha - RS              |  R$ 27.900,00 |
|               Glória - RS               |  R$ 39.606,51 |
|         Glória de Dourados - MS         |  R$ 18.700,00 |
|              Goianinha - RN             |  R$ 35.840,00 |
|              Goianésia - GO             |  R$ 50.145,45 |
|              Goiatuba - GO              |  R$ 49.561,39 |
|               Goioerê - PR              |  R$ 63.543,24 |
|               Goiânia - GO              |  R$ 66.745,05 |
|        Governador Valadares - MG        |  R$ 54.240,21 |
|               Gramado - RS              |  R$ 95.509,59 |
|              Gravataí - RS              |  R$ 42.880,61 |
|               Gravatá - PE              |  R$ 47.608,57 |
|              Guanambi - BA              |  R$ 64.170,69 |
|               Guaporé - RS              |  R$ 37.000,00 |
|             Guaramirim - SC             |  R$ 21.000,00 |
|          Guarantã do Norte - MT         |  R$ 35.000,00 |
|              Guarapari - ES             |  R$ 41.104,19 |
|             Guarapuava - PR             |  R$ 52.899,13 |
|              Guararema - SP             |  R$ 48.000,00 |
|            Guaratinguetá - SP           |  R$ 57.625,74 |
|               Guarujá - SP              |  R$ 37.914,07 |
|              Guarulhos - SP             |  R$ 48.410,35 |
|                Guará - DF               |  R$ 67.094,77 |
|               Guaxupé - MG              |  R$ 49.742,97 |
|               Guaíba - RS               |  R$ 60.650,00 |
|               Guaíra - SP               |  R$ 23.500,00 |
|               Guaíra - PR               |  R$ 36.350,00 |
|              Guidoval - MG              |  R$ 23.000,00 |
|               Gurupi - TO               |  R$ 52.865,31 |
|              Holambra - SP              |  R$ 24.475,00 |
|             Horizontina - RS            |  R$ 20.000,00 |
|             Hortolândia - SP            |  R$ 38.000,49 |
|                Ibaté - SP               |  R$ 65.000,00 |
|               Ibirité - MG              |  R$ 37.533,33 |
|               Ibirubá - RS              |  R$ 78.763,78 |
|              Ibitinga - SP              |  R$ 40.987,93 |
|               Ibiúna - SP               |  R$ 68.968,75 |
|               Igarapé - MG              |  R$ 30.122,22 |
|               Iguape - SP               |  R$ 28.000,00 |
|               Iguaçu - CE               |  R$ 37.936,25 |
|                Iguaí - BA               |  R$ 63.000,00 |
|                Ijuí - RS                |  R$ 67.105,49 |
|            Ilha Solteira - SP           |  R$ 60.000,00 |
|              Ilhabela - SP              |  R$ 28.300,00 |
|               Ilhéus - BA               |  R$ 58.777,78 |
|             Imperatriz - MA             |  R$ 63.459,06 |
|               Indaial - SC              |  R$ 55.949,50 |
|             Indaiatuba - SP             |  R$ 53.713,04 |
|               Inhumas - GO              |  R$ 26.950,00 |
|              Ipatinga - MG              |  R$ 62.866,78 |

## Qual a cidade que possui mais ofertas do produto?

In [169]:
query_job = client.query("""
                         SELECT cidade, UF, COUNT(id) as total
                         FROM dataset_icarros.all_cars 
                         GROUP BY cidade, UF
                         ORDER BY total DESC
                         LIMIT 1
                         """)
results = query_job.result()
t = PrettyTable(['Cidade', 'Total'])
for row in results:
    t.add_row(['{} - {}'.format(row.cidade, row.UF), '{}'.format(row.total)])
display(HTML('<h3>Cidade com mais ofertas do produto {}:</h3>'.format(modelo2)))
print(t)

+----------------+-------+
|     Cidade     | Total |
+----------------+-------+
| São Paulo - SP | 26459 |
+----------------+-------+

## Liste os 5 mais baratos e o mais caro.

In [170]:
query_job = client.query("""
                         SELECT versao, ano, km, cidade, UF, preco
                         FROM dataset_icarros.all_cars 
                         ORDER BY preco ASC
                         LIMIT 5
                         """)
results = query_job.result()
t = PrettyTable(['Versão', 'Cidade', 'Ano', 'Km', 'Preço'])
print()
for row in results:
    t.add_row(['{}'.format(row.versao), 
               '{} - {}'.format(row.cidade, row.UF),
               '{}'.format(row.ano), 
               '{}'.format(row.km), 
               'R$ {:,.2f}'.format(row.preco).replace('.', '|').replace(',', '.').replace('|', ',')])
display(HTML('<h3>5 mais baratos:</h3>'))
print(t)

+---------------------+-------------------+------------+--------+-------------+
|        Versão       |       Cidade      |    Ano     |   Km   |    Preço    |
+---------------------+-------------------+------------+--------+-------------+
|      Gol BX 1.6     |   Campinas - SP   | 1982/ 1982 |  N/D   | R$ 3.800,00 |
| Monza Sedan SLE 1.8 |   Arapongas - PR  | 1984/ 1984 | 757445 | R$ 3.900,00 |
|      Gol C 1.6      |   Guarulhos - SP  | 1987/ 1987 | 250000 | R$ 3.900,00 |
|  Uno Mille Brio 1.0 |   Caieiras - SP   | 1992/ 1992 | 130000 | R$ 3.911,00 |
|    Uno Mille 1.0    | Porto Alegre - RS | 1991/ 1991 | 150000 | R$ 3.990,00 |
+---------------------+-------------------+------------+--------+-------------+

In [173]:
query_job = client.query("""
                         SELECT versao, ano, km, cidade, UF, preco
                         FROM dataset_icarros.all_cars
                         ORDER BY preco DESC
                         LIMIT 1
                         """)
results = query_job.result()
t = PrettyTable(['Versão', 'Cidade', 'Ano', 'Km', 'Preço'])
for row in results:
    t.add_row(['{}'.format(row.versao), 
               '{} - {}'.format(row.cidade, row.UF),
               '{}'.format(row.ano), 
               '{}'.format(row.km), 
               'R$ {:,.2f}'.format(row.preco).replace('.', '|').replace(',', '.').replace('|', ',')])
display(HTML('<h3>O mais caro:</h3>'))
print(t)

+----------------------+----------------+------------+-----+-----------------+
|        Versão        |     Cidade     |    Ano     |  Km |      Preço      |
+----------------------+----------------+------------+-----+-----------------+
| Huracan 5.2 LP 610-4 | Fortaleza - CE | 2014/ 2015 | 866 | R$ 1.690.000,00 |
+----------------------+----------------+------------+-----+-----------------+

In [177]:
query_job = client.query("""
                         SELECT COUNT (*) as total FROM (
                             SELECT DISTINCT cidade, UF
                             FROM dataset_icarros.all_cars 
                             WHERE CIDADE IS NOT NULL AND CIDADE <> ''
                             GROUP BY cidade, UF
                             ORDER BY cidade
                         )
                         """)
results = query_job.result()  # Waits for job to complete.
# print(results.result())
t = PrettyTable(['Total de Cidades'])
for row in results:
    t.add_row(['{}'.format(row.total)])
display(HTML('<h4>Quantas cidades possuem anúncios do produto {}?</h4>'.format(modelo2)))    
print(t)

+------------------+
| Total de Cidades |
+------------------+
|       836        |
+------------------+

In [176]:
query_job = client.query("""
                         SELECT COUNT (*) as total FROM (
                             SELECT DISTINCT UF
                             FROM dataset_icarros.all_cars 
                             WHERE UF IS NOT NULL AND UF <> ''
                             GROUP BY UF
                             ORDER BY UF
                         )
                         """)
results = query_job.result()
t = PrettyTable(['Total de Estados'])
for row in results:
    t.add_row(['{}'.format(row.total)])
display(HTML('<h4>Quantos estados possuem anúncios do produto {}?</h4>'.format(modelo2)))    
print(t)

+------------------+
| Total de Estados |
+------------------+
|        27        |
+------------------+